apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - currencyservice.yaml
  - frontend.yaml
  - productcatalogservice.yaml
  - cartservice.yaml
images:
  - name: adservice
    newName: docker.io/kencharos/google-samples-microservices-demo/adservice
    newTag: v0.10.2

  - name: cartservice
    newName: ddevroy/cartservice
    newTag: latest

  - name: checkoutservice
    newName: docker.io/kencharos/google-samples-microservices-demo/checkoutservice
    newTag: v0.10.2

  - name: currencyservice
    newName: devroy/currencyservice
    newTag: latest

  - name: emailservice
    newName: docker.io/kencharos/google-samples-microservices-demo/emailservice
    newTag: v0.10.2

  - name: frontend
    newName: devroy/frontend 
    newTag: latest

  - name: paymentservice
    newName: docker.io/kencharos/google-samples-microservices-demo/paymentservice
    newTag: v0.10.2

  - name: productcatalogservice
    newName: devroy/productcatalogservice
    newTag: latest

  - name: recommendationservice
    newName: docker.io/kencharos/google-samples-microservices-demo/recommendationservice
    newTag: v0.10.2

  - name: shippingservice
    newName: docker.io/kencharos/google-samples-microservices-demo/shippingservice
    newTag: v0.10.2
