name: Frontend CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup kubeconfig
    - name: Set kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

    # Deploy (use existing image)
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/frontend \
        server=devroy/frontend:471 -n default

        kubectl rollout status deployment/frontend -n default
